version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-go_gqlgen_fx}
    volumes:
      - ./.postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER:-jamboree}", "-d", "${POSTGRES_DB:-jamboree}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
