version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-jolt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-jolt}
      POSTGRES_DB: ${POSTGRES_DB:-jolt}
    volumes:
      - ./.postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER:-jolt}", "-d", "${POSTGRES_DB:-jolt}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - "5432:5432"
