// Generated by https://quicktype.io

import { Movie } from "./movie";
import { Tv } from "./tv";

export interface Person {
  adult: boolean;
  gender: number;
  id: number;
  known_for: Array<Movie | Tv>;
  known_for_department: string;
  media_type: "person";
  name: string;
  popularity: number;
  profile_path: string;
}
